### ISSUE TITLE
TH15: Extra - starting at Boss Nonspell 2, 3, 6 and 7 isn't accurate

### ISSUE THREAD

**Issue by webbedspace** [ack7139/thprac#49] opened 2021-11-15 17:10 UTC
Hecatia Lapislazuli has an approx. 1-second animation where she switches heads. This animation occurs *after* her healthbar appears, and she *can* be damaged during it. However, when starting at these nonspells, the animation doesn't occur.

**Comment by ack7139** [comment] 2021-11-16 17:05
Hecatia is not Sekibanki. She switches bodies, not heads.
Anyway, this won't be fixed since that's how thprac treats most spells/non-spells: item drops, animations, and waiting time are cut to save time between retries. While this causes slight inaccuracy regarding boss health and remaining time, it's neglectable compared to the inconsistency caused by player's/bosses' movement, along with other random factors. There are certainly exceptions (Satori's BoWaP, for example), but I don't think Hecatia's non-spells fall into that category.

**Closed by ack7139** 2021-11-16 17:05 UTC
